name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test-lin-mac:
    if: ${{ false }}
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { rust: stable,            os: macos-latest }
        - { rust: stable,            os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          rust-version: ${{ matrix.rust }}
          command: test

  test-win:
    name: Test Rust stable on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install openssl
        run: |
          vcpkg install openssl:x64-windows-static-md
          vcpkg install sqlite3:x64-windows-static-md
          vcpkg integrate install
      - name: test
        uses: actions-rs/cargo@v1
        with:
          rust-version: stable
          command: test

  nux_arm7:
    if: ${{ false }}
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target armv7-unknown-linux-gnueabihf
